### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by rose1264** [newyork-anthonyng/faster-mta#20]
I could help with the accessibility.

**Comment by newyork-anthonyng** [comment]
Hi @rose1264

Thank you! 

I was thinking we can do an accessibility audit first. The automated accessibility checks show no issues; could you do a manual audit? 

You can use a screenreader like [`VoiceOver`](https://www.apple.com/voiceover/info/guide/_1124.html) or [`ChromVox`](https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en).
Go through the website and note down any issues you find. Then we can go from there.

Let me know if you have any questions.

**Comment by rose1264** [comment]
Hi Anthony,

I've tested through the app with VoiceOver and ChromeVox. Btw, I think VoiceOver is  more convenient with the navigation shortcut. 

Good job on the right HTML tags of headings and links! they came with default features and performed well in the screen reader.

The main issue we could start with is the hamburger menu. 'home' and 'map' links inside the hamburger menu are still focusable when the menu is closed. This behavior is very confusing because when I tab through the page, the focus just disappeared from the screen. 

The solution would be using tabindex. Set the tabindex to '-1' at the beginning. When the hamburger menu is open, focus the links with focus() method. 

I could open a PR if you want!

Rose

**Comment by newyork-anthonyng** [comment]
Sounds good! One issue we would still have is that if the menu is open, the user can still tab outside of the menu. 

![tabbing](https://user-images.githubusercontent.com/14035529/48593518-204b6180-e91b-11e8-9db3-af7b179a6615.gif)

Ideally, we want to:
* trap the user inside the menu ([see focus trapping](https://hiddedevries.nl/en/blog/2017-01-29-using-javascript-to-trap-focus-in-an-element))
* allow user to press `ESCAPE` to close the menu

And it'd be awesome if you could open up a PR for this. Let me know if you have any questions.

**Comment by newyork-anthonyng** [comment]
Closed by #23
